spring.application.name=taskmanager

# H2 Veri Taban? Ayarlar?
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Uygulama ba?lad???nda tablolar? otomatik olu?tursun
spring.jpa.hibernate.ddl-auto=update

# H2 Konsolunu aktif et (Taray?c?dan bakabilmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Konsolda SQL sorgular?n? görmek istersen
spring.jpa.show-sql=true